# File: .github/workflows/workflow.yml

on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/1ec622b5-ad99-46a1-8d70-9abfec01a0d5/resourceGroups/contoso-traders-rg1725864               
        scopes-ignore: |
          /subscriptions/1ec622b5-ad99-46a1-8d70-9abfec01a0d5/resourceGroups/contoso-traders-rg1725864/providers/microsoft.authorization
